<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="species.xsl"?>
<!DOCTYPE species[<!ELEMENT species (mod+)><!ELEMENT mod (specie+,id?,link?)><!ATTLIST mod name CDATA "Z-UNDEFINED"><!ELEMENT specie (imgOn?,imgOff?,default?)><!ATTLIST specie value CDATA #REQUIRED><!ATTLIST specie name CDATA #IMPLIED><!ELEMENT default ANY><!ELEMENT imgOn EMPTY><!ATTLIST imgOn src CDATA "img/tab_other_select.png"><!ELEMENT imgOff EMPTY><!ATTLIST imgOff src CDATA "img/tab_other.png"><!ELEMENT tab ANY><!ELEMENT title (#PCDATA)><!ELEMENT sub (#PCDATA)><!ELEMENT html ANY>]>
<species warning="true"><mod><specie value="albinopenguin" name="Albino Penguin"/></mod><mod><specie value="alicorn"/></mod><mod name="Elithian Races Mod" author="Aegonian [THEA]"><id steam="850109963"/><specie value="avikan"/><specie value="terrakin"/><specie value="droden"/><specie value="trink"/></mod><mod><specie value="batpony"/></mod><mod><specie value="catus"/></mod><mod><specie value="clownkin"/></mod><mod><specie value="demon"/></mod><mod><specie value="eeveetwo" name="Eevee Two"/></mod><mod><specie value="kineptic"/></mod><mod><specie value="manicpenguin"/></mod><mod><specie value="moogle"/></mod><mod><specie value="munari"/></mod><mod><specie value="pegasus"/></mod><mod><specie value="pengvolt"/></mod><mod><specie value="plaguin"/></mod><mod><specie value="ponex"/></mod><mod><specie value="puffin"/></mod><mod><specie value="pyroguin"/></mod><mod><specie value="robopenguin" name="Robo Penguin"/></mod><mod><specie value="rockhopperpenguin" name="Rock Hopper Penguin"/></mod><mod><specie value="rodentia"/></mod><mod><specie value="shade"/></mod><mod><specie value="su_gem" name="Su Gem"/></mod><mod><specie value="troll"/></mod><mod><specie value="unicorn"/></mod><mod><specie value="vanillapenguin" name="Vanilla Penguin"/></mod><mod name="Race - Munari" author="Motionless"><id steam="739676461"/><specie value="neko"/></mod></species>